blank_issues_enabled: false
contact_links:
  - name: GenX Community Support
    url: https://github.com/GenXHQ/genx/discussions
    about: Please ask and answer questions here.
  - name: GenX Documentation
    url: https://genx.art/docs
    about: Please check out the documentation here.
